### ISSUE TITLE
Exporting "dump" after schema layout

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#3]
The "diff" is a bit of a mess if the assignment ordering has changed - everything is out of sync. Line it up properly.

**Comment by kodecharlie** [comment]
To confirm issue, see attached snapshot of a diff I just generated by exporting schema.ttl to "data/template/vocabulary.dump".  After moving around two of the assays, and deleting another, it seems every remaining assay has widespread differences (mainly showing up as Removed items).

<img width="697" alt="screen shot 2018-01-05 at 7 33 54 pm" src="https://user-images.githubusercontent.com/1671748/34636108-749d2084-f24f-11e7-94d9-d6d1e677ede1.png">

**Comment by kodecharlie** [comment]
Update:  I'm still on this issue, mainly drilling down into the pertinent data structures.  I think I may know what going on:  namely, that EditSchema.rebuildTree() does not update some of the data structures incorporated in the comparison logic in CompareVocabTree.

**Comment by kodecharlie** [comment]
My hunch:  methods like Schema.moveAssignment do a shallow copy on editMove, leading to legacy data being used during the tree-diff comparisons.  Please advise how you want to proceed.

**Comment by gedeck** [comment]
I'm currently looking too at the Schema.java file too for this unrelated issue: https://github.com/cdd/bioassay-express/issues/625. I found one peculiar thing that cloning an Assignment created some information about the group nesting that wasn't there before. 

There are a few tests for this file in bioassay-express `test/com.cdd.bao.template.SchemaTree.java` and some of them cover the clone method. However the `equals` implementation aren't always complying with the Java contract. In particular the `Assignment` class only compares the fields of the objects and not the position in the tree structure (=branch up to node and subtrees attached to node). 

@aclarkxyz, I think it's time to move the tests into bioassay-template where they really belong.

**Comment by kodecharlie** [comment]
Hunch:  CompareVocabTree.setupTree's inner-loop should not condition on "tree location".  When stuff is moved, it essentially means we are comparing apples and oranges.  I haven't figured out the fix yet, but that inner-loop is my current target.

**Comment by kodecharlie** [comment]
Per comment above, I removed the gating logic on tree location; an OutOfMemory exception triggered -- a reasonable outcome given that we essentially promoted linear logic to polynomial.  But I still think the basic premise of not conditioning on tree location is sound.  Instead, we need a fix that looks at root URIs, like this:
```
String rootUri1 = (tree1.tree.getFlat().length <= 0) ? null : tree1.tree.getFlat()[0].uri;
String rootUri2 = (tree2.tree.getFlat().length <= 0) ? null : tree2.tree.getFlat()[0].uri;
if (!StringUtils.equals(rootUri1, rootUri2)) continue;
```

**Comment by kodecharlie** [comment]
Proposal:  do a 2-phased diff.  Phase 1:  use same inner-loop logic, but skip over trees whose root URIs do not match, saving tree2 (ie, currently editable schema);  Phase 2:  use same inner-loop logic, but only iterate over saved tree2's from Phase 1.

I believe this should work and avert any OutOfMemory exception.
