### ISSUE TITLE
Need a "Find" feature

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#30]
For locating content in the template; especially for large templates like AZ, it's very tedious to locate a term, especially if it's not the label that's being searched (e.g. the URI).

**Comment by kodecharlie** [comment]
I will defer the "Find Next" feature for now.

My plan is to employ the FX Dialog widget (similar to LookupPane), but I require
some guidance on what you want to see in the dialog.  Clearly, the initial iteration will
have a text field for entering a simple string.  Do you also want check buttons, per your
earlier note, that enable/disable searches on URI / label / description?   Anything else?

And how do you wish to render the results list?

**Comment by aclarkxyz** [comment]
Actually I hadn't thought that far ahead. I think the best strategy would be to implement the most simple thing possible, and we'll see if that's sufficient. Maybe just input the text, and maybe some checkboxes, then the action button could either select the next occurrence, or barf if there is none. It's probably fine to keep it as a modal dialog.

Keep in mind that the template editor is mostly used internally, and the alternative to what you're about to build is... nothing. So that bar isn't all that high :-)

**Comment by kodecharlie** [comment]
Additional questions:
- How do you want to trigger the Find dialog?
- To clarify, are we searching a schema that is loaded and being edited, one or more ontologies, or something else that might also be specified in the Find dialog?

**Comment by aclarkxyz** [comment]
Trigger should be Edit|Find / Cmd-F (making it as conventional as possible)

The Find feature should just apply to the schema contents. The biggest pain point is when you have a schema that has ~200 assignments on the left hand side, and figuring out if any of the groups/assignments have a particular name, property label or URI fragment requires stepping through them all, one at a time.

It could have 2 modes depending on selection: if the left hand side has focus, search group/assignment set. If right hand side (DetailPane) has focus, search through the values that are in the current assignment. The latter functionality is less important, but might be useful on occasion, and consistent with expectations.

Might be an idea to have the dialog title indicate what it's searching (i.e. groups & assignments vs. values within an assignment).

**Comment by aclarkxyz** [comment]
Sounds good. You may not need a "results" pane though - you could just change focus to the next item. That would be a lot less work, and may be good enough.

**Comment by kodecharlie** [comment]
Progress:  set up simple modal dialog; now figuring out how to search through tree of group / assignments.

**Comment by kodecharlie** [comment]
We have a couple of options for discovering and traversing item matches:
- Scan the tree for ALL matching groups / assignments, and save a list of matching Nodes (or Node IDs).
- If "Find Next" succeeds, halt the search, save the matching Node, and then if "Find Next" is pressed again, proceed with InOrder traversal of the tree, starting with last matching Node.

Clearly, the latter option has the bonus of averting a complete tree-scan from the outset, but does require a little more leg-work on the logic side.

Let me know if you have a preference.

**Comment by aclarkxyz** [comment]
The latter is probably better; keep it simple. Performance is not going to be an issue.

**Comment by kodecharlie** [comment]
Actually I used the first option before seeing your comment...  I can adjust as needs be.
