### ISSUE TITLE
Lookup dialog: buttons

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#34]
The parts of the detail view that offer a URI allow that URI to be looked up in a dialog box by way of the menu, or pressing Cmd-L. This is convenient enough but a bit confusing sometimes because the subject of the dialog depends on the selection, and properties-vs-values bring up a completely different section of the hierarchy.

To make it more clear, especially for new users, the following UI sections:

![image](https://user-images.githubusercontent.com/6205603/33836400-51f1d5a4-de57-11e7-928d-915481ab2aa7.png)

... should be supplemented with a lookup button:

![image](https://user-images.githubusercontent.com/6205603/33836489-8914963e-de57-11e7-9846-5dc0c57cbb3c.png)

**Comment by gedeck** [comment]
This has nothing to do with this issue, however these links never give me anything useful. They always just open the full XML. Is that the intention? In the link above, I cannot even find BAO_0002854. Only find this:
```
<rdf:Description rdf:about="http://purl.obolibrary.org/obo/UBERON_0002854">
<obo:IAO_0000412 rdf:resource="http://purl.obolibrary.org/obo/uberon.owl"/>
</rdf:Description>
```

**Comment by aclarkxyz** [comment]
The thing that happens when a URI is used as a URL is entirely at the discretion of the owner... results vary quite widely.

**Comment by kodecharlie** [comment]
Should this button be labeled "Lookup URI" to match the corresponding menu label?  I presume the lookup operation remains the same (ie, this is strictly a UI enhancement).

**Comment by aclarkxyz** [comment]
(1) Whatever works best, (2) Yes.

**Comment by kodecharlie** [comment]
Cmd-L, or "Lookup Name", surfaces a panel with results.
Cmd-U, or "Lookup URI", does invoke the right callback (actionLookupURI), but does not as yet surface any panel.

Aside from adding the button here, does the callback actionLookupURI() need to change at all so as to surface a panel?
