### ISSUE TITLE
Template veracity check

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#35]
It is currently a little to easy to make templates that have mistakes that will cause problems when they are used. For example, property/group URIs that are missing or malformed; property/group URIs that are duplicated within their context; assignments that are expecting a tree of URI values but have none, or none that are valid, etc.

There should be a verification scan for these errors; it should probably be user-initiated (e.g. in a menu, which brings up a report of problems), but it could be integrated more deeply into the UI (e.g. a warning notifier).

**Comment by gedeck** [comment]
That would be good. For BAE, we can include this check as part of the configuration validation.

**Comment by aclarkxyz** [comment]
Not really: I want the veracity check to operate on the _datastructure_, not the file format. The purpose of this particular issue is for runtime interactive use, i.e. the user picks a menu option, and it lets them know if they've made any obvious mistakes (duplicates, invalid URIs, etc.).

**Comment by kodecharlie** [comment]
Is it enough to say, "Everywhere in EditSchema, we need to validate after `stack.changeSchema()` is called" ?  @gedeck's comment suggest this is an offline validation, but @aclarkxyz's comment implies runtime-check.  Please clarify.

**Comment by aclarkxyz** [comment]
For this particular issue, I'd like the checking to be on request by a user, and it'll give helpful feedback if there's anything obviously wrong. It doesn't have to be too slick, it's just a thing that we actually need, because it's easy to make mistakes and hard to find them (when templates get large, especially).

For Peter's comment, I think you just need to put the verification algorithm into a separate class that's easy to access programmatically, so we'll re-use it in other parts of the code... two birds and one stone, and all that.

**Comment by kodecharlie** [comment]
Offline versus runtime checks:  now clear.  Thx.

Can we make some simple assertion such as:  whenever `stack.changeSchema()` is called, we need to validate the template (ie, runtime data structure housing the template)?

If this simple assertion is not sufficient, is there another that would be?

**Comment by aclarkxyz** [comment]
I'm inclined to say leave it as an "opt in" feature for now, and we can consider making it more proactive later. The template editor is an internal / expert tool... if we want to raise the UI/UX bar later we can, but for now we just need to address things that are making our own lives more difficult than they need to be.

**Comment by kodecharlie** [comment]
I just found the class `TemplateChecker`.  Can we appropriate this logic for certifying changes at runtime to the currently editable schema?

**Comment by aclarkxyz** [comment]
Well spotted, I'd forgotten about that. You could indeed repurpose it to provide systematic feedback; I think it covers most of the common/obvious problem cases.

**Comment by kodecharlie** [comment]
From Alex:

> It doesn't need to be tied to edit events - a global menu button for "Check My Schema Please" will suffice, and it can bring attention to problems in some fashion. Options are open for how to do that... a dialog box with text-style information that the user has to parse manually would be an improvement over what we have right now (i.e. nothing), and we can always make it better later.
