### ISSUE TITLE
Show alternate labels and URLs...

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#39]
... in various parts of the UI, especially tooltips. Also allow alternate labels to be searched in the lookup dialogs.

**Comment by kodecharlie** [comment]
I looked through *.ttl and *.json files but did not see reference to "alternate labels".
Please clarify where alternate labels can be found.

We have tooltips in the edit-pane.  Where else do you want to see tooltips?
Also, in which "various parts of the UI" do you want to surface said labels / URLs?

(I could make a few calculated guesses here, but would prefer more precision
on where I focus efforts.)

**Comment by aclarkxyz** [comment]
The alternate labels are in Vocabulary - they get loaded up out of the constituent ontology files. One place to display them is in the tooltips, which currently only show descriptions. The other important part is the lookup dialogs: when the user types part of a label, it finds/matches part of the string, so they can select that property/value. The match criteria should apply to alternate labels as well.

It might be worth some brief thought about a visual clue to show that the match applied to the non-primary label, but this might be more of an optional nice to have. If the search works, and the tooltip shows the other labels, our presumed-expert user base should be able to join the dots.

**Comment by kodecharlie** [comment]
Several points:
- It looks like alternate labels are available through SchemaTree.Node.altLabels.  We should be able to grab that data structure from the tree on the left-side of the editor, and propagate relevant labels to DetailPane.  Do you see any performance issues in calling this method:

    `SchemaTree tree = new SchemaTree(assn, Vocabulary.globalInstance());`

- On visual cues:  it seems like our Find command in the editor should highlight matching elements in the DetailPane.  For alternate labels attached to some GUI node, I'm not sure yet how best we could capture that kind of match.

**Comment by aclarkxyz** [comment]
No need to use SchemaTree, you can just use vocab.getAltLabels

I think the Find currently only works on group/property labels, which don't really do synonyms (or rather, we replace the ontology label with our own... so for all practical purposes, we only need to care when the user is trying to find one of them in the sprawling ontology. So it's the same utility as for values: when doing a lookup, make sure they can find based on any of the values; and if the tooltip shows the alternate labels, the user has a way of figuring out why the match.

**Comment by kodecharlie** [comment]
Do you have a preference where in the DetailPane you want to surface
the altLabels in a tooltip?  I think the `Lookup` button makes sense.  The
question then is what else should be in that tooltip?  How about:

    Match URI, name, description or these alternate labels:  "foo", "bar", etc.

**Comment by aclarkxyz** [comment]
This is what the tooltip looks like in BAE:

![image](https://user-images.githubusercontent.com/6205603/35293139-d3d6c286-0040-11e8-87b9-e7ee44330b77.png)

... so in the absence of any other preference, make it similar to that.

BTW, I'm referring to the tooltip for an individual result. Any tip stuff for the query is at your discretion, it's overly critical.

**Comment by kodecharlie** [comment]
I don't understand your last comment:  `I'm referring to the tooltip for an individual result. Any tip stuff for the query is at your discretion, it's overly critical.`

A search result now is merely one of the matching group / assignments.  Why would a tooltip on a result be any different from the tooltip that is not a result?  It's the same DetailPane -- we just need to figure out where in the DetailPane to surface the altLabels.  I thought the `Lookup` button was one good place.  If you prefer elsewhere, I'm open.

**Comment by aclarkxyz** [comment]
Your suggested text [Match URI, name, description or these alternate labels:  "foo", "bar", etc."] seemed more like instructions rather than the description of a result... but as long as you're not confused as to which is which, I'm sure it's all good :-)

**Comment by kodecharlie** [comment]
Should our "Find" ignore case?  IMHO that is more user-friendly.

**Comment by aclarkxyz** [comment]
Yes.

**Comment by kodecharlie** [comment]
I've implemented the relevant logic.  However, for testing, it's not clear to me how you would
annotate values/groups/assignments with alternate labels.  It looks like `data/ontology/bao_complete_merged.owl` characterizes the `alternative term` annotation.  But so far as I can tell, none of the ontology files actually references that annotation.

What do you propose for testing?  I will go ahead and push logic out to branch "issue-#35" for your perusal.  But we need to test more.

**Comment by kodecharlie** [comment]
Here's my proposal:
- LookupPanel will feature a checkbox next to the Search input field; checkbox will be labeled "Use alternate terms".  If checked, the search includes alternate terms in the lookup; otherwise not.
- We surface a tooltip as you mouse-over each row / result in the LookupPanel.  The tooltip will include (i) URI abbreviation and (ii) list of alternate terms.
