### ISSUE TITLE
Edge condition:  Assay Stats should raise warning dialog when no assays.

### ISSUE THREAD

**Issue by kodecharlie** [cdd/bioassay-template#53]
See snapshot below.  "Assay Stats" to my thinking really does not make sense
when there are no assays.

**Comment by kodecharlie** [comment]
<img width="695" alt="screen shot 2018-01-19 at 10 14 13 am" src="https://user-images.githubusercontent.com/1671748/35165087-c841e35c-fd01-11e7-9a4e-e5a5e4de30b8.png">

**Comment by aclarkxyz** [comment]
Agreed. The "Assays" feature is semi-deprecated anyway: it was necessary when the BAE didn't exist, but now we don't use it anymore. It may be useful to the open source community though, so I haven't removed it, but we don't to actively push it forward.

**Comment by kodecharlie** [comment]
Based on comments, I am closing this issue.
