### ISSUE TITLE
Deprecation term

### ISSUE THREAD

**Issue by aclarkxyz** [cdd/bioassay-template#68]
Parse a new kind of predicate in the ontology files: `bat:replaceWith`

As the ontologies are loaded, all of the triples indicating `{old} bat:replaceWith {new}` will be collected into a map (old:new = one-to-many; in `Vocabulary.java`).

Terms that appear in the subject are omitted from the tree building.

A new section needs to be defined for the `vocab.dump` file for enumerating these replacements. This will be subsequently used by BAE for dynamic substitution.

**Comment by kodecharlie** [comment]
Can we subsume this issue under issue #756 from BAE (ie, the remapping feature)?  If so, I think we should close this issue as soon as the #756 merge completes.

**Comment by aclarkxyz** [comment]
Sounds good.

**Comment by kodecharlie** [comment]
#756 is now merged (in both bax / bae repos).
